### ISSUE TITLE
URL does not exist?

### ISSUE THREAD

**Issue by MapZombie** [app-generator/flask-now-ui-dashboard#1]
I am getting this 404 redirect message with every app-seed flask app:

> The URL you were looking for does not seem to exist.
> Define the new page in /pages

I'm following the readme to the tee and have installed all dependencies. What is going on here, why can't I render any page? Thanks.

**Comment by Jspascal** [comment]
Facing same issue. Did you found a solution?

**Comment by app-generator** [comment]
Hello @Jspascal 
Sorry for the delay :), we were busy.  
Please re-test the app. 

P.S. Soon the app will be migrated to a better architecture with blueprints, jinja2 template inheritance and much more. 

P.S. Thank you for our our products.
