### ISSUE TITLE
Get picture and show picture.

### ISSUE THREAD

**Issue by MagicMarcus100** [app-generator/flask-now-ui-dashboard#2]
Hi.
I use your dasboard - it's unique ;-)
This is my first contact with flask and I have a request: I need to download and save a picture from one subpage and then display it on this subpage. How to do it? 
I managed to save the image but the page is displayed itself (with picture) without the dashboard:
`            print("Image to send:", filename)`
`            return render_template("/pages/c19r.html", user_image = filename)`
Thank you
Marcus

**Comment by rosoftdeveloper** [comment]
Hello @MagicMarcus100,
Thanks for using our products. 
At first look, this is not a product issue, please join the community on [Discord](https://discord.gg/fZC6hup) to talk with other developers in the community. 

I will close the issue.
